#pragma once

#define MAIN_WINDOW_CLASS_NAME L"Main Window Class"
#define MAIN_WINDOW_TITLE      L"Paracosm"

#define MAIN_WINDOW_OPTIONAL_STYLES 0
#define MAIN_WINDOW_STYLE           WS_OVERLAPPEDWINDOW

#define MAIN_WINDOW_SIZE_W 1280
#define MAIN_WINDOW_SIZE_H 720
#define MAIN_WINDOW_POS_X  CW_USEDEFAULT
#define MAIN_WINDOW_POS_Y  CW_USEDEFAULT

